package org.yologn.RhQuestEditor;

import java.util.*;
import java.util.stream.Collectors;

/**
 * Created by Admin on 27.04.2017.
 */
public class TypesMap {
    static LinkedHashMap<String, Integer> optionTypesMap =  initOptionTypesMap();
    static LinkedHashMap<String, Integer> attributeTypesMap = initAttributeMap();
    public static LinkedHashMap getOptionTypesMap()
    {
        return optionTypesMap;
    }
    public static LinkedHashMap getAttributeTypesMap()
    {
        return attributeTypesMap;
    }
    private static LinkedHashMap initOptionTypesMap() {
        LinkedHashMap<String, Integer> OptionTypesMap = new LinkedHashMap<String, Integer>();

        OptionTypesMap.put("NULL", 0);
        OptionTypesMap.put("Strength", 1);
        OptionTypesMap.put("Dexterity", 2);
        OptionTypesMap.put("Intelligence", 3);
        OptionTypesMap.put("Psyche", 4);
        OptionTypesMap.put("Vitality", 5);
        OptionTypesMap.put("Agility", 6);
        OptionTypesMap.put("Weapon Attack", 7);
        OptionTypesMap.put("Armor defense", 8);
        OptionTypesMap.put("Health Recovery", 9);
        OptionTypesMap.put("Mana Recovery", 10);
        OptionTypesMap.put("Mobility", 11);
        OptionTypesMap.put("Attack Speed", 12);
        OptionTypesMap.put("Critical Rate", 13);
        OptionTypesMap.put("Health absorbtion", 14);
        OptionTypesMap.put("Mana absorbtion", 15);
        OptionTypesMap.put("Resistance Start", 16);
        OptionTypesMap.put("Blazing resistance", 16);
        OptionTypesMap.put("Frozen resistance", 17);
        OptionTypesMap.put("Darkness resistance", 18);
        OptionTypesMap.put("Divine resistance", 19);
        OptionTypesMap.put("Resistance End", 19);
        OptionTypesMap.put("Accuracy", 20);
        OptionTypesMap.put("Evasion", 21);
        OptionTypesMap.put("Defence rate", 22);
        OptionTypesMap.put("Health", 23);
        OptionTypesMap.put("Mana", 24);
        OptionTypesMap.put("Magic attack rate", 25);
        OptionTypesMap.put("Melle attack rate", 26);
        OptionTypesMap.put("Ranged attack rate", 27);
        OptionTypesMap.put("Physical defense", 28);
        OptionTypesMap.put("Magic defense", 29);
        OptionTypesMap.put("Weight rate", 30);
        OptionTypesMap.put("Potion recovery rate", 31);
        OptionTypesMap.put("SKILL_MANA_DEC_RATE", 32);
        OptionTypesMap.put("ATTACK_NULL_RATE", 33);
        OptionTypesMap.put("Damage drop", 34);
        OptionTypesMap.put("No arrows rate", 35);
        OptionTypesMap.put("Heal rec rate", 36);
        OptionTypesMap.put("Elemental force rate", 37);
        OptionTypesMap.put("Cooldown decrease", 38);
        OptionTypesMap.put("Block rate", 39);
        OptionTypesMap.put("Reflection", 40);
        OptionTypesMap.put("Pet level", 41);
        OptionTypesMap.put("PET_FEED_HIBYTE", 42);
        OptionTypesMap.put("PET_FEED_LOWBYTE", 43);
        OptionTypesMap.put("Pet hunger count", 44);
        OptionTypesMap.put("Pet feed count", 45);
        OptionTypesMap.put("Weight", 46);
        OptionTypesMap.put("Pet dead", 47);
        OptionTypesMap.put("Health rate", 48);
        OptionTypesMap.put("Mana rate", 49);
        OptionTypesMap.put("Damage reflect", 50);
        OptionTypesMap.put("Min damage drop", 51);
        OptionTypesMap.put("Stun resist rate", 52);
        OptionTypesMap.put("Poison resist rate", 53);
        OptionTypesMap.put("HP recovery rate", 54);
        OptionTypesMap.put("MP Recovery rate", 55);
        OptionTypesMap.put("HP success rate", 56);
        OptionTypesMap.put("MP success rate", 57);
        OptionTypesMap.put("Fish grade", 58);
        OptionTypesMap.put("Critical dmg reduction", 59);
        OptionTypesMap.put("Pet style", 60);
        OptionTypesMap.put("Pet pickup option", 61);
        OptionTypesMap.put("Mall item time 1", 62);
        OptionTypesMap.put("Mall item time 2", 63);
        OptionTypesMap.put("Mall item disable", 64);
        OptionTypesMap.put("Mall item usage time", 65);
        OptionTypesMap.put("Mall item timestap", 66);
        OptionTypesMap.put("Mall item timestamp 2", 67);
        OptionTypesMap.put("Seal item", 68);
        OptionTypesMap.put("Guildwar reward", 69);
        OptionTypesMap.put("All status", 70);
        OptionTypesMap.put("All attack rate", 71);
        OptionTypesMap.put("All defence", 72);
        OptionTypesMap.put("Marriage ring casting casting time", 73);
        OptionTypesMap.put("Pet skill cooldown time", 74);
        OptionTypesMap.put("Item grade", 75);
        OptionTypesMap.put("Fixed exchange item", 76);
        OptionTypesMap.put("Pet rebirth count", 77);
        OptionTypesMap.put("Pet rebirth", 78);
        OptionTypesMap.put("Reinforce level", 79);
        OptionTypesMap.put("Exchange mall timestamp", 80);
        OptionTypesMap.put("Exchange mall timestamp 2", 81);
        OptionTypesMap.put("OWNER_CHARID_MSB", 82);
        OptionTypesMap.put("OWNER_CHARID_LSB", 83);
        OptionTypesMap.put("Tool use count", 84);
        OptionTypesMap.put("All attack reinforced", 85);
        OptionTypesMap.put("All defence reinforced", 86);
        OptionTypesMap.put("CUR_DURABILITY", 87);
        OptionTypesMap.put("DUR_TIME", 88);

        OptionTypesMap.put("IOT_DECREASE_PHYSICS_DEFENCE", 0x59);
        OptionTypesMap.put("IOT_DECREASE_MAGIC_DEFENCE", 0x5A);
        OptionTypesMap.put("IOT_DECREASE_SKILL_DAMAGE_RATE", 0x5B);
        OptionTypesMap.put("IOT_DONT_MOVE_CONDITION_REDUCE_RATE", 0x5C);
        OptionTypesMap.put("IOT_ALL_ATTACK_FORCE", 0x5D);
        OptionTypesMap.put("IOT_PENETRATE_DEC_DMG_RATE", 0x5E);

        OptionTypesMap.put("IOT_INC_CRITICAL_DMG_RATE", 0x5F);
        OptionTypesMap.put("IOT_PENETRATE_DEF_RATE", 0X60);
        OptionTypesMap.put("IOT_PVP_ATTACK_RATE", 0X61);
        OptionTypesMap.put("IOT_PVP_DEFENCE_RATE", 0X62);
        OptionTypesMap.put("IOT_MAX_NUM", 0X63);
        OptionTypesMap.put("None", -1);
        return OptionTypesMap;
    }
    private static LinkedHashMap initAttributeMap() {
        LinkedHashMap<String, Integer> AttributeMap = new LinkedHashMap<String, Integer>();

        AttributeMap.put("ITEM_TYPE", 0);
        AttributeMap.put("DESCRIPTION", 1);
        AttributeMap.put("Weight", 2);
        AttributeMap.put("Price", 3);
        AttributeMap.put("Sellrpcei", 4);
        AttributeMap.put("Leve req", 5);
        AttributeMap.put("Str req", 6);
        AttributeMap.put("Dex req", 7);
        AttributeMap.put("Int req", 8);
        AttributeMap.put("Current stack", 9);
        AttributeMap.put("Max stack", 10);
        AttributeMap.put("Rank", 11);
        AttributeMap.put("Inventory", 12);
        AttributeMap.put("Slot", 13);
        AttributeMap.put("Damage", 14);
        AttributeMap.put("Attack speed", 15);
        AttributeMap.put("Attack range", 16);
        AttributeMap.put("Miss", 17);
        AttributeMap.put("Critical rate", 18);
        AttributeMap.put("Block rate", 19);
        AttributeMap.put("Defence", 20);
        AttributeMap.put("Health", 21);
        AttributeMap.put("Mana", 22);
        AttributeMap.put("Cooldown reduction", 23);
        AttributeMap.put("CURE_LEVEL", 24);
        AttributeMap.put("CURE_RATE", 25);
        AttributeMap.put("Casting time", 26);
        AttributeMap.put("USE_LEVEL", 27);
        AttributeMap.put("SLOT_NUM", 28);
        AttributeMap.put("DISCOUNT_RATE", 29);
        AttributeMap.put("DISCOUNT_SUCCESS_RATE", 30);
        AttributeMap.put("BUILD_TIME", 31);
        AttributeMap.put("USE_SKILL_LEVEL", 32);
        AttributeMap.put("Mount speed", 33);
        AttributeMap.put("Mount casting time", 34);
        AttributeMap.put("Mount race", 35);
        AttributeMap.put("Success chance", 36);
        AttributeMap.put("PET_LEVEL1_RATE", 37);
        AttributeMap.put("PET_LEVEL2_RATE", 38);
        AttributeMap.put("PET_LEVEL3_RATE", 39);
        AttributeMap.put("PET_FEED1", 40);
        AttributeMap.put("PET_FEED2", 41);
        AttributeMap.put("PET_HUNGRY_TIME_MINUTE", 42);
        AttributeMap.put("PET_MAX_HUNGRY_COUNT", 43);
        AttributeMap.put("FEED_COUNT", 44);
        AttributeMap.put("FEED_TIME_MINUTE", 45);
        AttributeMap.put("USE_MAX_LEVEL", 46);
        AttributeMap.put("MAX_WEIGHT_RATE", 47);
        AttributeMap.put("PET_WEIGHT1_RATE", 48);
        AttributeMap.put("PET_WEIGHT2_RATE", 49);
        AttributeMap.put("PET_WEIGHT3_RATE", 50);
        AttributeMap.put("MAX_WEIGHT", 51);
        AttributeMap.put("PET_REBIRTHCOST_LEVEL1", 52);
        AttributeMap.put("PET_REBIRTHCOST_LEVEL2", 53);
        AttributeMap.put("PET_REBIRTHCOST_LEVEL3", 54);
        AttributeMap.put("EXP_RECOVERY_RATE", 55);
        AttributeMap.put("NO_WEIGHT", 56);
        AttributeMap.put("NO_DROP", 57);
        AttributeMap.put("FISH_REWARD_GRADE", 58);
        AttributeMap.put("ITEMTYPE_LEVEL", 59);
        AttributeMap.put("Gender", 60);
        AttributeMap.put("FISHTOOL_PROBVALUE", 61);
        AttributeMap.put("Strength", 62);
        AttributeMap.put("Vitality", 63);
        AttributeMap.put("Intelligence", 64);
        AttributeMap.put("Psyche", 65);
        AttributeMap.put("Dexterity", 66);
        AttributeMap.put("Agilitiy", 67);
        AttributeMap.put("Melee attack", 68);
        AttributeMap.put("Ranged attack", 69);
        AttributeMap.put("Magic attack", 70);
        AttributeMap.put("Accuracy", 71);
        AttributeMap.put("Evasion", 72);
        AttributeMap.put("Physical def", 73);
        AttributeMap.put("Magic def", 74);
        AttributeMap.put("GM ONLY", 75);
        AttributeMap.put("ARMOR_DEFENCE_UNAVAILABLE", 76);
        AttributeMap.put("INITSTATUS_POINT", 77);
        AttributeMap.put("TIMER_TYPE", 78);
        AttributeMap.put("USE_AREA", 79);
        AttributeMap.put("USE_CRAFT_LEVEL", 80);
        AttributeMap.put("DURATIONTIME", 81);
        AttributeMap.put("LIMIT_UPPER", 82);
        AttributeMap.put("LIMIT_LOWER", 83);
        AttributeMap.put("GUILD_POINT", 84);
        AttributeMap.put("ATTITUDEON", 85);
        AttributeMap.put("SUBTYPE", 86);
        AttributeMap.put("CRAFT_TYPE", 87);
        AttributeMap.put("CONSERSTONE_PREMIUM", 88);
        AttributeMap.put("LIFEMANA", 89);
        AttributeMap.put("PET_LEVEL1_EXPVALUE_1", 90);
        AttributeMap.put("PET_LEVEL2_EXPVALUE_1", 91);
        AttributeMap.put("PET_LEVEL3_EXPVALUE_1", 92);
        AttributeMap.put("PET_LEVEL1_EXPVALUE_2", 93);
        AttributeMap.put("PET_LEVEL2_EXPVALUE_2", 94);
        AttributeMap.put("PET_LEVEL3_EXPVALUE_2", 95);
        AttributeMap.put("SKILLKIND_2ND", 96);
        AttributeMap.put("SKILLKIND_3RD", 97);
        AttributeMap.put("SKILLKIND_4TH", 98);
        AttributeMap.put("All stat", 99);
        AttributeMap.put("All attack", 100);
        AttributeMap.put("All def", 101);
        AttributeMap.put("ADD_DROPRATE", 102);
        AttributeMap.put("COL_EXP_RATE", 103);
        AttributeMap.put("COL_SPEED", 104);
        AttributeMap.put("COL_ADD_RARE_RATE", 105);
        AttributeMap.put("COL_ADD_NUM_RATE", 106);
        AttributeMap.put("COL_SHOW_RES", 107);
        AttributeMap.put("ABILITY_CRAFT_START_NOUSE", 108);
        AttributeMap.put("ABILITY_CRAFT_END_NOUSE", 109);
        AttributeMap.put("PET_LEVEL1_EXPVALUE_3", 110);
        AttributeMap.put("PET_LEVEL2_EXPVALUE_3", 111);
        AttributeMap.put("PET_LEVEL3_EXPVALUE_3", 112);
        AttributeMap.put("PET_LEVEL1_EXPVALUE_4", 113);
        AttributeMap.put("PET_LEVEL2_EXPVALUE_4", 114);
        AttributeMap.put("PET_LEVEL3_EXPVALUE_4", 115);
        AttributeMap.put("CRAFT_SKILLTYPE", 116);
        AttributeMap.put("CRAFT_EQUIPLIMIT", 117);
        AttributeMap.put("PET_RESTORATION", 118);
        AttributeMap.put("CONSERVATION_RATE", 119);
        AttributeMap.put("BOOSTER_TYPE", 120);
        AttributeMap.put("PRODUCT_GRADE", 121);
        AttributeMap.put("CRAFT_CP", 122);
        AttributeMap.put("CRAFT_MAXCP_DOWN", 123);
        AttributeMap.put("CRAFT_ACCIDENTRATE_DOWN", 124);
        AttributeMap.put("CRAFT_FAILRATE_DOWN", 125);
        AttributeMap.put("REINFORCE_VALUE", 126);
        AttributeMap.put("REINFORCE_SUCCESS_RATE", 127);
        AttributeMap.put("REINFORCE_FAIL_RATE", 128);
        AttributeMap.put("TOOL_USE_COUNT", 129);
        AttributeMap.put("MELEE_ATTACK_FORCE_2S", 130);
        AttributeMap.put("MAGIC_ATTACK_FORCE_2S", 131);
        AttributeMap.put("RANGE_ATTACK_FORCE_2S", 132);
        AttributeMap.put("ALL_ATTACK_FORCE_2S", 133);
        AttributeMap.put("PHYSICAL_DEFENCE_2S", 134);
        AttributeMap.put("MAGIC_DEFENCE_2S", 135);
        AttributeMap.put("ALL_DEFENCE_2S", 136);
        AttributeMap.put("PET_COMBINATION_ITEM_ID", 137);
        AttributeMap.put("BP_BONUS_RATE", 138);
        AttributeMap.put("FAKED_BATTLE_RANK", 139);
        AttributeMap.put("LIMIT_MAX_RANK", 140);
        AttributeMap.put("PET_REBIRTH_USE_LEVEL", 141);
        AttributeMap.put("ITEM_PIECE", 142);
        AttributeMap.put("ENCHANT_STONE_SUCCESS_RATE", 143);
        AttributeMap.put("PERIOD", 144);
        AttributeMap.put("PERIOD_TICKET", 145);
        AttributeMap.put("DURABILITY", 146);
        AttributeMap.put("REPAIR", 147);
        AttributeMap.put("REPAIRPRICE", 148);
        AttributeMap.put("PRICE_BY_IP", 149);

        AttributeMap.put("SAVE_CHANCE_ARRENDAL",163);
        //AttributeMap.put("IAT_CHR_SPEED", 0x96);

        AttributeMap.put("IAT_ITEM_NOTTRADE", 0x96);
        AttributeMap.put("IAT_ITEM_RANDOM_OPTION", 0x97);
        AttributeMap.put("IAT_INDUN_RESTRICT_VALUE", 0x98);
        AttributeMap.put("IAT_SKILL_MIN_LEVEL", 0x99);
        AttributeMap.put("IAT_SKILL_MAX_LEVEL", 0x9A);
        AttributeMap.put("IAT_ITEMUSE_MIN_LEVEL", 0x9B);
        AttributeMap.put("IAT_ITEMUSE_MAX_LEVEL", 0x9C);
        AttributeMap.put("IAT_PRICE_BY_BADGE", 0x9D);
        AttributeMap.put("IAT_PRODUCT_L_PLUS_RATE", 0x9F);
        AttributeMap.put("IAT_PRODUCT_M_PLUS_RATE", 0xA0);
        AttributeMap.put("IAT_PRODUCT_H_PLUS_RATE", 0xA1);
        AttributeMap.put("IAT_PRODUCT_VH_PLUS_RATE", 0xA2);
        AttributeMap.put("IAT_CONSERVE_PROBABILITY", 0xA3);
        AttributeMap.put("IAT_SPIRIT_WEAPON_EXP", 0xA4);
        AttributeMap.put("IAT_SPIRIT_WEAPON_LEVEL", 0xA5);
        AttributeMap.put("IAT_MELEE_ATTACK_FORCE_RATE", 0xA6);
        AttributeMap.put("IAT_MISSILE_ATTACK_FORCE_RATE", 0xA7);
        AttributeMap.put("IAT_MAGIC_ATTACK_FORCE_RATE", 0xA8);
        AttributeMap.put("IAT_MAX_LIFE_RATE", 0xA9);
        AttributeMap.put("IAT_UNTIL_LEVEL", 0xAA);
        AttributeMap.put("IAT_SUCCESS_PROBABILITY_DEFAULT", 0xAB);
        AttributeMap.put("IAT_PET_LEVEL1_MODEL", 0xAC);
        AttributeMap.put("IAT_PET_LEVEL2_MODEL", 0xAD);
        AttributeMap.put("IAT_PET_LEVEL3_MODEL", 0xAE);
        AttributeMap.put("IAT_PVP_DEFENCE_RATE", 0xAF);
        AttributeMap.put("IAT_MAX_NUM", 0xB0);
        AttributeMap.put("None", -1);
        return AttributeMap;
    }
    public static Object getKeyFromValue(Map hm, Object value) {
        for (Object o : hm.keySet()) {
            if (hm.get(o).equals(value)) {
                return o;
            }
        }
        return null;
    }
}
